### PR TITLE
stream renaming support for camcan, big debug, Tibor PRs

### PR DESCRIPTION
**Pull request by jooh**
_Currently running tests, don't merge yet_

This PR will:

* Ensure that AA runs without SPM on the path, and that the AA-specified SPM version is respected. There was a bug where various SPM functions were called before SPM was added to the path by AA, which caused crashes if the user didn't have SPM on the path, and incorrect behaviour if the user had a different SPM version on their path than what they had specified in AA with the spmdir option. It was basically possible for the same user script to end up using different SPM versions in localsingle and qsub.
* Stop crashes when new ifconfig version is encountered in e.g. aas_writedoneflag
* Add the 'isrenameable' flag to many ROI processing modules (necessary for CamCAN pipeline)
* Update CBU defaults to run on new Centos7 cluster
* Include other open PRs from Tibor (#202, #203, #204) to save us having to run the tests more than once.

Special request: Could one of the mac users run the basic tests (`aatest` with no arguments), ideally including bootstrapping a new user parameters XML by moving ~/.aa/aap_parameters_default.xml somewhere else? I had a user who attempted to run AA on a mac at a workshop last year and it seemed not to work out of the box. I will run the 'CBU' tests as usual.

### CODE REVIEW

**Comment by jooh** [comment]
Ok, so I think the first test failure is @tiborauer's - in aa_user_bids I crash with the following: 

```
MODULE aamod_diffusionfromnifti RUNNING: Find diffusion input files from nifti for /imaging/jc01/aa/aa_demo/bids_ds114/aamod_diffusionfromnifti_00001/sub-01/dwi_test
 executing
Reference to non-existent field 'hdr'.
Error in aamod_diffusionfromnifti (line 30)
        headerfile = series.hdr;
Error in aa_feval (line 15)
    [varargout{:}]=feval(funcname,varargin{:});
Error in aa_feval_withindices (line 4)
[aap,resp]=aa_feval(mfile_alias,aap,task,ci{:});
Error in aa_doprocessing_onetask (line 185)
            [aap,resp]=aa_feval_withindices(mfile_alias,aap,task,indices);
Error in aaq_qsub_debug (line 42)
                aa_doprocessing_onetask(obj.pool.Jobs(eii).Tasks.InputArguments{:}) 
30          headerfile = series.hdr;```

**Comment by tiborauer** [comment]
Hi @jooh, Have you used the aa_demo (ds114) or the cbu example?

**Comment by jooh** [comment]
This crash is in aa_user_bids_ds000114.m, one of the general examples. I am contradicting myself a bit - I said I would run the CBU tests but I am in fact starting with the general tests since they run faster for debugging.

**Comment by tiborauer** [comment]
Hi @jooh, I have just submitted a PR to your branch to debug diffusionfromnifti

**Comment by jones-michael-s** [comment]
Hello all,

Just an update: we're working on testing the PR but it might be awhile (aatest has never worked for us so we need to fix that first).

I'll keep you posted,
Mike

**Comment by tiborauer** [comment]
AFAIC, it is good to be merged.

**Comment by jooh** [comment]
Sorry, hit some cluster configuration problems at cbu. Going to get the tests running properly today.

**Comment by jooh** [comment]
@tiborauer NB I changed the SLURM job submission arguments for max filter to something that works here at CBU. But I notice you added these lines so please let me know if this is going to break things on your HPC.

**Comment by tiborauer** [comment]
@jooh I cannot see any issue. Besides, I/we use(d) the MEG pipeline only at the CBU so far. :)

**Comment by jooh** [comment]
Ok, all tests pass over here so I'm going to merge this. @jones-michael-s I suggest you open an issue when you have a chance to try out aatest, and we'll deal with that in a separate update.

**Pull request merged**
