### PR TITLE
CLEANUP - modulenames

### PR DESCRIPTION
**Pull request by tiborauer**

### CODE REVIEW

**Comment by tiborauer** [comment]
Considering the lack of criticism as approval, I am going to merge this PR by the end of the week.

**Comment by ethanknights** [comment]
Sounds good I think 

The renaming of modules will lead to lots of manual cosmetic changes to old tasklist.xml files (e.g. Cam-CAN used a bunch of roi extraction modules throughout multiple streams for its different releases) but that's not a major issue, and I support adopting a more structured naming scheme (I am assuming these module names are more consistent than before!).

As for deleting modules. I didn't see these listed in Cam-CAN's latest tasklist, so that shouldn't cause a compatibility problem for us (perhaps they are old WIP modules anyway(?)):
```
aa_modules/aamod_coreg_structural2template.m
aa_modules/aamod_coregisterstructural2template.m #dupe?
```

**Comment by tiborauer** [comment]
Thanks, @ethanknights, so you are saying it is good to go?

**Review by jones-michael-s — APPROVED** [review]
Looks good to me.

**Comment by tiborauer** [comment]
Thank you, @jones-michael-s. I am going to merge now.

**Pull request merged**
