### PR TITLE
Index by session number for series in epifromnifti

### PR DESCRIPTION
**Pull request by TamerGezici**
In relation to issue: (https://github.com/automaticanalysis/automaticanalysis/issues/331#issuecomment-1152928368)

### CODE REVIEW

**Comment by tiborauer** [comment]
I am afraid you have to reduce the disk size requested for CI. Let me know if you have trouble with that, and I can submit a PR to your repo.

**Comment by TamerGezici** [comment]
> I am afraid you have to reduce the disk size requested for CI. Let me know if you have trouble with that, and I can submit a PR to your repo.

I don't have any experience with setting up CI. The ones I used before were all set up by others.  I couldn't find anything related to it on google for reducing disk either. If you can do it for me that would be nice. Otherwise you can just copy my code and make your own PR, that would also be OK.

**Comment by tiborauer** [comment]
Please, update your PR with changes in the main repo. Make a reverse PR from [automaticanalysis:master](https://github.com/automaticanalysis/automaticanalysis) to [TamerGezici:master](https://github.com/TamerGezici/automaticanalysis).

**Comment by TamerGezici** [comment]
I updated my fork with the upstream master branch. I was just going to say that I'm not sure how I'm supposed to trigger the CI, but it looks like it does it on its own already.

**Comment by tiborauer** [comment]
Since you are a new contributor, your PRs do not trigger CI, and they need approval I just granted.

**Comment by TamerGezici** [comment]
Looks like the tests have passed.

**Comment by TamerGezici** [comment]
I also made a commit which addresses this issue: https://github.com/automaticanalysis/automaticanalysis/issues/335

**Comment by tiborauer** [comment]
Ideally, you submit different PRs (from a different branches) for different issues. Otherwise, you always have to restart testing (as now).

**Comment by tiborauer** [comment]
Ideally, you submit different PRs (from a different branches) for different issues. Otherwise, you always have to restart testing (as now).

**Comment by tiborauer** [comment]
Ideally, you submit different PRs (from a different branches) for different issues. Otherwise, you always have to restart testing (as now).

**Comment by TamerGezici** [comment]
> Ideally, you submit different PRs (from a different branches) for different issues. Otherwise, you always have to restart testing (as now).

I knew but I forgot to make a new branch for this. Sorry. I guess it's too late now but next time I'll make a new branch.

**Pull request merged**
