### PR TITLE
Bugfixes related to Getting started

### LINKED ISSUE #257: BUG - Allow empty fsldir entry.
https://github.com/automaticanalysis/automaticanalysis/discussions/254#discussioncomment-1471279

Item 1 from the linked comment:
Most examples can run with just AA and SPM, except that the presence of FSL is implicit in some places.

In aamod_segment8/diag, a T1 file is read from aap.directory_conventions.fsldir. This gives an error when fsl is not present. The same file is hardcoded in 5 other places in the AA code! In one of those places (aamod_freesurfer_register), also an SPM provided alternative is given. Applying that alternative in aamod_segment8 allows the examples that use segment8 to run to completion. 
Proposed: put the hardcoded filename in one place, a getter function that also has something like a allow_alternative input option. And use that function in all 5 places, with the allow_alternative option set depending on where the function is called from.

In aa_provenance, the fls version file is read, without checking if it exists. This gives an error when fsl is not present. Adding a check on the presence of the fsldir and the version file prevents the error. 
Proposed: add this check.

### LINKED ISSUE #258: BUG - aas_processBIDS fails on filepaths that have a . somewhere in it
https://github.com/automaticanalysis/automaticanalysis/discussions/254#discussioncomment-1471279

In particular, in two places in aas_processBIDS, an expression like [~,n,~] = fileparts(strtok(cfname{1},'.'));` is used. This does not work correctly for stripping a file extension, when there is a . somewhere in the path name. Proposed: probably a double fileparts can be used, have a quick discussion on that.

### LINKED ISSUE #259: BUG - Module capitalization in aa_example_helloworld_model
The module aamod_biascorrect_meanEPI is referenced, whereas the actual xml file in aa_modules is aamod_biascorrect_meanepi.xml. This gives an error. Proposed: Fix capitalization.

https://github.com/automaticanalysis/automaticanalysis/discussions/254#discussioncomment-1471279

### LINKED ISSUE #260: BUG - reqpath creation with trailing filesep character
The batch option uses the reqpath. The cellindex way used to compose the reqpath, will fail to add the 'main' folder of a certain toolbox, if the folder is specified with a trailing pathsep character (i.e. a / on linux). Thus the batch jobs can error on failing to find certain functions, as they are not on the path for the tasks matlab process. Proposed Fix reqpath creation to take possible trailing pathseps into account.

https://github.com/automaticanalysis/automaticanalysis/discussions/254#discussioncomment-1471279

### PR DESCRIPTION
**Pull request by AljenU**
Fixes for various bugs found during Getting started.

Closes #257 
Closes  #258 
Closes  #259 
Closes  #260 
Partially solves #261

### CODE REVIEW

**Comment by jones-michael-s** [comment]
So far this passes aatest_ds000114_fmri for me.

I tested this on my local machine (OS X 10.14 and R2018b). I'm still getting up to speed on CI. It's currently using a virtual Linux machine, yes? Will we eventually want to add virtual Windows and Macs?

**Comment by tiborauer** [comment]
It is possible to run CI on Windows and MacOS:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Review by tiborauer — CHANGES_REQUESTED** [review]
@AljenU, Did not we agree on using `pathsep` instead of ":" in MATLAB path?

**Comment by AljenU** [comment]
> 
> 
> So far this passes aatest_ds000114_fmri for me.
> 
> I tested this on my local machine (OS X 10.14 and R2018b). I'm still getting up to speed on CI. It's currently using a virtual Linux machine, yes? Will we eventually want to add virtual Windows and Macs?

Yes, we do want to add Macs and some Windows. Some notes on that, probably better to discuss that in #272

**Comment by AljenU** [comment]
> 
> 
> @AljenU, Did not we agree on using `pathsep` instead of ":" in MATLAB path?

That will be part of the Windows-compatibility changes. For this set, it is only about changes for Getting Started on Linux.

**Review by tiborauer — APPROVED** [review]

**Pull request merged**
