### PR TITLE
added acq_details options

### PR DESCRIPTION
**Pull request by jones-michael-s**
This is a simple one-file PR -- I've added some processing flags to aas_processBIDS, tweaked string processing in one place to fix a bug when one event name is contained in another, and done some cosmetic clean up.

### CODE REVIEW

**Comment by jones-michael-s** [comment]
I have two rather substantial PRs ready to go after this (one includes modification of all the modeling modules, and the other is a half-dozen new modules to implement motion scrubbing). 

At first I though submitting these as three smaller PR was a good approach (hence this one-file PR of our BIDS tweaks) but in hindsight maybe this is a bad idea? It occurs to me I might be tripling the number of times the test suite has to get run.

If there's a consensus that one big PR would make testing easier, I could do that instead.

Any thoughts?
Mike

**Comment by tiborauer** [comment]
Although, there are some practicality in submitting one PR, I also think independent substantial changes deserve separate PRs. 
If these changes affect well-defined areas in the code and well-specified use-cases, then we can test them separately - even in parallel.

**Comment by tiborauer** [comment]
I can see a few useful settings, however, it is not clear from the beginning what are the default settings. Since they are not part of the app_paremetersets. I can also see that backward compatibility is ensured by using `isfield(...)`, you may be able to hit two birds with one stone, if you would define defaults settings at the beginning (and in one place), if they are not specified. Similarly to https://github.com/automaticanalysis/automaticanalysis/blob/f202cef65b5a2b9a57d30bb32bcda1da50882f15/aa_engine/aas_processBIDS.m#L50-L60

**Comment by jones-michael-s** [comment]
Okay, I added initialization that hopefully clarifies the defaults.

Tested locally; all looks good on my end...

**Pull request merged**
