### PR TITLE
Mapindices between AAPs when doing a remote connection

### PR DESCRIPTION
**Pull request by TamerGezici**
Solves: https://github.com/automaticanalysis/automaticanalysis/issues/381

Sorry for the late PR. 

I have been using this for awhile and have not ran into any issues.

It may be worth checking how it reacts in the CI.

### CODE REVIEW

**Review by tiborauer — APPROVED** [review]

**Comment by TamerGezici** [comment]
I noticed the test failed.

https://github.com/automaticanalysis/automaticanalysis/actions/runs/8345014752/job/22838861147

But I don't know where to look for the error. Can you tell me, please?

**Comment by tiborauer** [comment]
You can click on the little arrow in front of the lines.

**Comment by TamerGezici** [comment]
Was the error alright? Because I could not figure out what the error was when I checked.

**Comment by tiborauer** [comment]
I took a look, and I suspect it was a bug in FieldTrip, which - hopefully - has been corrected since then. 
I rerun the test.

**Pull request merged**
