### PR TITLE
minor bugfixes on aa_export_toBIDS

### PR DESCRIPTION
**Pull request by jones-michael-s**
Took export_to_BIDS out for a test drive. Here's a few bugfixes...

### CODE REVIEW

**Comment by tiborauer** [comment]
It seems quite all right, but I am not so sure about https://github.com/automaticanalysis/automaticanalysis/blob/6de823ac951b532042eec562bb01228304e591a0/aa_toolbox/aa_export_toBIDS.m#L244
because it deletes `src_dummy` from which the pipeline  but leaves `src`, the temporary file.

**Comment by jones-michael-s** [comment]
I could be wrong but don't we want to keep src? In my test pipeline it was the .nii that gets generated at the end of aamod_covert_epi.

I discovered this problem by running export_toBIDS twice. On the second run, the copyfile crashes because src was deleted from aamod_convert_epi in the previous pass.

**Comment by tiborauer** [comment]
It depends on the use case:

1. If there is no dummy scan, then `src` is indeed the converted epi. In that case, `src_dummy` will not be created and nothing will be deleted.
2. If there is any dummy scan, then `src` and `src_dummy` point to the temporary file (dummy + epi) and the dummy file, respectively,

**Comment by jones-michael-s** [comment]
Are you able to run export_toBIDS twice on your data? This is what alerted us to the problem.

**Comment by tiborauer** [comment]
Yes, I can run `aa_export_toBIDS` twice on e.g. both the aa demo and the bids114 datasets. However, both requires some tweaking:
- aa demo has a short subjectname, which causes https://github.com/automaticanalysis/automaticanalysis/blob/1a68e1d52067c0ad6ad8f08a812158c2f4e462d1/aa_toolbox/aa_export_toBIDS.m#L120 crash, so it has to be omited.
- bids114 demo has not got a full header which causes  https://github.com/automaticanalysis/automaticanalysis/blob/1a68e1d52067c0ad6ad8f08a812158c2f4e462d1/aa_toolbox/aa_export_toBIDS.m#L256-L258 crash, so they have to be omited.

However, both issues are irrrelevant regarding the current PR. Still, they should be fixed, of course.

**Comment by jones-michael-s** [comment]
> Yes, I can run aa_export_toBIDS twice on e.g. both the aa demo and the bids114 datasets. 

Interesting. I'll look into what is peculiar about my data (which crashes)...

**Comment by jones-michael-s** [comment]
Okay, finally got some time to look into this. I think the line in question should actually read:

`  copyfile(src,dest); gzip(dest); delete(dest); if (exist('src_dummy','var') && ~isempty(src_dummy)), delete(src); clear src_dummy; end       
`

The hiccup is src_dummy gets created by checking if any of the modules have a "dummyscan" output stream (line 225) -- this will be true for any pipeline that contains aamod_convert_epis even if you don't actual *create* any dummyscans. So we need an additional check if scr_dummy is empty. That fixed the crash on my machine.

**Comment by tiborauer** [comment]
This looks good to me. Do you want to update the PR?

**Comment by jones-michael-s** [comment]
> This looks good to me. Do you want to update the PR?

Nah -- it was my screw up.

I'll push a correction...

**Pull request merged**
