### PR TITLE
Feature downloaddemo rework and tests

### PR DESCRIPTION
**Pull request by AljenU**
- Rework downloaddemo to a simpler interface, be windows compatbile, and make it possible to automatically test the download of the demo datasets.
- Add test for all downloaddemo datasets
- Rework tutorial_1 to use downloaddemo and be automatically testable
- Add test for tutorial_1
- Add test that only installs minimal tooling (only aa and spm) and no data, and run it on examples that should work with such a minimal install (and have been adapted so they can run automatically, currently only tutorial_1)

Fix issue #275 
Fix issue #305

### CODE REVIEW

**Review by tiborauer — APPROVED** [review]

**Comment by tiborauer** [comment]
It seems the CI has overwritten one artifact with the other: https://github.com/automaticanalysis/automaticanalysis/actions/runs/1507207336

**Review by tiborauer — CHANGES_REQUESTED** [review]
It seems the CI has overwritten one artifact with the other: https://github.com/automaticanalysis/automaticanalysis/actions/runs/1507207336

**Comment by AljenU** [comment]
> It seems the CI has overwritten one artifact with the other: https://github.com/automaticanalysis/automaticanalysis/actions/runs/1507207336

Ah, it took me while, but i see what you mean now: test_log.txt is created three times, but since it is uploaded with the same name, only one is available at the end. Will look into it.

**Comment by tiborauer** [comment]
Thank you, @AljenU. Would it be possible to have the log for the downloaddemo_test more informative? Right now it says
testExamples/downloaddemo_test(dataset=value1) and testExamples/downloaddemo_test(dataset=value2). Could it tell the dataset ID, instead?

**Comment by AljenU** [comment]
Hey Tibor,

I updated the PR to have named datasets. That should be all for this PR I think?

Regards,
Aljen

________________________________

**Review by tiborauer — APPROVED** [review]

**Pull request merged**
