### PR TITLE
Review: 3D nifti for retrieve input

### PR DESCRIPTION
**Pull request by TamerGezici**
Issue mentioned here: 

https://github.com/automaticanalysis/automaticanalysis/issues/345#issuecomment-1282368804

Can you please review this? The script works fine, but I don't know if there could be something I'm missing @tiborauer

### CODE REVIEW

**Comment by tiborauer** [comment]
While your solution seems valid and not breaking anything for 4D NIfTI, it reduces performance by not utilizing the chunk-wise transfer. The original concept is that aa collects files to move into chunks before the transfer, and your solution for the 3D NIfTI simply transfers files one-by-one. 

N.B.: I have made some changes in the AROMA to make sure it works (also for the CI). You should merge these changes into your branch.

**Comment by TamerGezici** [comment]
I see. How can we chunk 3D NIfTI? Can we compress the 3D NIfTI's belonging to a single run into several single NIfTI files and move them? Does this sound like a good solution?

**Comment by TamerGezici** [comment]
Additionally, the main issue here is the current script doesn't work for 3D NIfTI at all. So, sure the performance will be worse for 3D NIfTI, that's there, but at least it will work?

**Comment by tiborauer** [comment]
Sorry for not being clear: here, chunking means sending more than one file at once. Here, it is hard-coded for 64 (`chunksize=64;`) for some reason (I have not written the code). The reason is that rsync may be able to handle more than one file effectively by compressing them. it is built in rsync and does not require extra code.
On the other hand, `aas_coppfromremote` mostly uses (the platform-independent) `copyfile`, so it does not matter anymore, I guess.
To be honest, this part of the code is quite convoluted and may require some substatial reworking (not now, of course!).

All in all, I think we can merge your PR as is; however, you may want to merge the current central repo first to have a clean CI.

**Comment by TamerGezici** [comment]
Done.

Please check if this commit is fine: https://github.com/automaticanalysis/automaticanalysis/commit/d53d83cc2d7247e6ec29afab960d8983cb3c68f9

I think I had local changes before pulling the upstream branch before AROMA. So I ended up doing a local merge. If this messes something up, I can re-commit from a blank slate.

**Pull request merged**
