### PR TITLE
5.7.0

### PR DESCRIPTION
**Pull request by tiborauer**
Major implementations
- M/EEG connectivity statistics and diagnostics with (scripted) BNV
- TDT: feature selection
- CONN toolbox with decoding using TDT
- toolboxes: global workspace variables, documentation

A few small fixes and enhancements
- M/EEG: contrasts on source level
- For aas_getsourcestage with branched tasklists. It has one (plausible) caveat that one branchname MUST NOT contain the other + '_', which would not be good for readability anyway.
- omit .github folder when adding aa to path
- options for aas_checktasksettingconsistency. Useful when using it as a standalone workflow diagnostic tool

### CODE REVIEW

**Comment by jones-michael-s** [comment]
Running into some problems with toolbox initialization when testing this.

For example:

`FAIL - aatest_ds000114_fmri.m
aatest_ds000114_fmri.m had an error: Too many input arguments.
in /Users/peellelab/automaticanalysis/aa_tools/toolboxes/bwtClass.m (line 23)
in /Users/peellelab/automaticanalysis/aa_tools/toolboxes/aas_inittoolbox.m (line 22)
in /Users/peellelab/automaticanalysis/aa_engine/aa_init.m (line 119)
in /Users/peellelab/automaticanalysis/aa_engine/aa_doprocessing.m (line 79)
in /Users/peellelab/automaticanalysis/developer/testscripts/aatest_ds000114_fmri.m (line 75)
in /Users/peellelab/automaticanalysis/developer/aa_test.m (line 156)
in /Users/peellelab/automaticanalysis/developer/aa_test.m (line 121)`

I suspect this is a parameter file issue. Here is my current bwt toolbox setup:

```
<toolbox desc='Toolbox with implemented interface in extrafunctions/toolboxes' ui='custom'>
    <name desc='Name corresponding to the name of the interface without the "Class" suffix' ui='text'>bwt</name>
    <dir ui='dir'>/Users/peellelab/MATLAB_THIRDPARTY/BrainWavelet</dir>
</toolbox>
```

My previous version had an extraparameters block that I removed (cf. `aap_parameters_defaults_CBSU.xml`). However, aa also crashes if the extraparameter block is present.

**Comment by tiborauer** [comment]
I am afraid I forgot to update your toolboxes. The `doKeepInPath` parameter has been removed because it has no effect. This was the missing bit to make the code and the documentation fully aligned. It did not raise a flag because they are not part of the CI (yet - WIP). 
I have updated them.

**Comment by jones-michael-s** [comment]
That seems to have got it working.

Thanks much.

**Comment by tiborauer** [comment]
I am sorry for the lack of transparency.

**Comment by jones-michael-s** [comment]
This passed all tests (run locally). Good to merge.

**Review by jones-michael-s — APPROVED** [review]
Passed all local test.

**Comment by tiborauer** [comment]
Thanks, @jones-michael-s. However, I'd rather first sort out the new tests including AROMA and scrubbing. I think I have sorted them out. I currently run the test on [my repo](https://github.com/tiborauer/automaticanalysis/tree/WASHU), and if it passes, I submit a PR. 
So, please, hold off with merging this one.

**Comment by tiborauer** [comment]
I take a look at the conflict.

**Comment by tiborauer** [comment]
Now it is ready to be merged.

**Pull request merged**
