### PR TITLE
Fix path logging in aas_shell

### PR DESCRIPTION
**Pull request by TamerGezici**
Fixes logging in `aas_shell ` due to the backslashes in windows due to them also being an escape character in `cprintf`

### CODE REVIEW

**Comment by TamerGezici** [comment]
Ignore the first commit, please. I noticed that it may be better to do this without changing the value of `cmd`

**Comment by tiborauer** [comment]
Shall we merge it as is?

**Comment by TamerGezici** [comment]
> Shall we merge it as is?

Yes, the last commit should be fine.

**Comment by tiborauer** [comment]
You mean "with the last commit", right? I cannot merge a single commit from a PR but the whole PR with all the commits in order.

**Comment by TamerGezici** [comment]
Otherwise it shouldn't be a problem, as the code from the first commit is pretty much re-written.

**Comment by tiborauer** [comment]
I am not worried about the "mess" as long as the final code is efficient and tidy. The "mess" only shows the work.

So if you are happy with the code as is (i.e., after all the commits), then I can merge it.

**Comment by TamerGezici** [comment]
> I am not worried about the "mess" as long as the final code is efficient and tidy. The "mess" only shows the work.
> 
> So if you are happy with the code as is (i.e., after all the commits), then I can merge it.

Should be fine for merging then. Thanks.

**Pull request merged**
