### PR TITLE
Update 'meg' to 'meeg' for legacy aa_modules

### PR DESCRIPTION
**Pull request by ethanknights**
To rerun Cam-CAN's MEG aa, I found myself running into problems with the old aa_modules using 'meg' rather than the newer 'meeg' convention. 

This PR suggests updating to 'meeg' for these 2 modules I was actively using (but there's other cases where this could apply in the future I guess):
```
aamod_meg_convert.xml
aamod_meg_maxfilter.xml
```

The number of small commits over the last few days were a long-winded way of me figuring out that I needed to update this almost everywhere to get the streams read successfully by `aareport()` (i.e. in the filenames, .xml tags, .xml in/out streams and parts (not all aspects, like the neuromag commands etc) of the .m functions).

@tiborauer, I think you said you weren't aiming to support these modules anymore? But it'd be useful for me if these 2 could be updated, so I don't need to work on a branch for MEG permanently. What do you think?

### CODE REVIEW

**Comment by tiborauer** [comment]
Good work, @ethanknights. Could you also update the MEEG example in the CBU folder and make sure it runs through (at the CBU)?

**Comment by ethanknights** [comment]
Thanks!
Yes ok - will be in touch about the CBU MEEG example.

**Comment by ethanknights** [comment]
As requested, the above commit updated the CBU meg example .xml / .m (so it uses the 'meeg', not 'meg', convention).

To recap, specifically this PR:
- changed 'meg' to the new meeg convention to get the 2 modules working I needed.
- updated remaining 'meg' modules used in the CBU's meg example to 'meeg' too.
- updated examples/cbu/aa_user_meg.m & .xml based on changed modules above.

Some notes:
1. I haven't ran the cbu meg demo to completion, as it crashes during the penultimate stage: `aamd_meg_denoise_ICA_2_applytrajectory`
I spent more time than I care to admit trying to figure out why, but no luck. I don't think the PR introduced this though, as the same error occurs with a fresh git clone of the current aa repo. Error is copied to the bottom if interested (I think the channel strings in the data don't match those from the imported topographies file). Happy to leave PR open if someone wants to take a look, but I don't think I'll manage to fix myself, apologies!
If any consolation, my basic meg pipeline did work with these changes, so these modules appear to be in a working state (this pipeline included meg convert, and meg maxfilter modules across 3 branches for movement compensation, spatial transformations etc). 

2. aamod_meg_epoch is renamed with a slightly longer name than other modules (aamod_meeg_epoch_meg) as a compromise, because this file already exists: `aamod_meeg_epcoh`.

3. Arguably, referring to some of the changed modules as 'meeg' is misleading because they only apply to 'meg'. Nonetheless my view is that changing all modules to follow the 'meeg' convention is beneficial, because it simplifies stream in/outputs (e.g. no need to rename in/outputs to 'meeg' for every branch)  


Error from running `examples/cbu/aa_user_meg.m`
```
MODULE aamod_meg_denoise_ICA_2_applytrajectory RUNNING: MEG ICA denoise 2: Apply trajectory matrix for /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_2_applytrajectory_00001/S1/run1
Loaded datecheck was 1B2M2Y8AsgTpgAmY7PhCfg== and calc bw5qvgmilKurStBoGiMD6g==
 retrieving stream meg from /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_convert_00001/S1/run1 to /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_2_applytrajectory_00001/S1/run1
 retrieving stream topography from /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_importfilesasstream_00002 to /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_2_applytrajectory_00001
 retrieving stream meg_ica from /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_1_00001/S1/run1 to /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_2_applytrajectory_00001/S1/run1
 executing
Warning: could not send tracker information for "startup"
Load stream from file /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_2_applytrajectory_00001/S1/run1/stream_meg_inputto_aamod_meg_denoise_ICA_2_applytrajectory_00001.txt...
Load stream from file /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_2_applytrajectory_00001/S1/run1/stream_meg_ica_inputto_aamod_meg_denoise_ICA_2_applytrajectory_00001.txt...
Load stream from file /imaging/henson/users/ek03/aa/aa_demo/meg/aamod_meg_denoise_ICA_2_applytrajectory_00001/stream_topography_inputto_aamod_meg_denoise_ICA_2_applytrajectory_00001.txt...
WARNING: Cannot find VEOG062 in channels nor in separate file
WARNING: Cannot find HEOG061 in channels nor in separate file
WARNING: Cannot find ECG063 in channels nor in separate file
WARNING: No temporal reference has been found! Temporal artifacts cannot be removed!
Bandpass filtering from 1.000000e-01 to 40 Hz (warning - can fail)
Warning: instability detected - reducing the 4th order filter to an 3th order filter
Warning: instability detected - reducing the 4th order filter to an 3th order filter
Warning: instability detected - reducing the 4th order filter to an 3th order filter
Warning: instability detected - reducing the 4th order filter to an 3th order filter
Bandpass filtering from 1.000000e-01 to 40 Hz (warning - can fail)
Warning: instability detected - reducing the 4th order filter to an 3th order filter
Warning: instability detected - reducing the 4th order filter to an 3th order filter
Warning: instability detected - reducing the 4th order filter to an 3th order filter
Warning: instability detected - reducing the 4th order filter to an 3th order filter

SPM12: spm_eeg_montage (v7643)                     17:31:28 - 12/04/2021
========================================================================
Warning: copying input chantype to montage
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/forward/ft_apply_montage.m' at line 110

Warning: copying input chanunit to montage
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/forward/ft_apply_montage.m' at line 128

Warning: copying input chantype to montage
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/forward/ft_apply_montage.m' at line 110

Warning: copying input chanunit to montage
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/forward/ft_apply_montage.m' at line 128

creating layout from cfg.elec
creating layout for eeg system
creating layout from cfg.grad
undoing the custom balancing for the gradiometer definition
Warning: copying input chantype to montage
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/forward/ft_apply_montage.m' at line 119
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/private/undobalancing.m' at line 37
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/ft_prepare_layout.m' at line 1275
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/ft_prepare_layout.m' at line 592

Warning: copying input chanunit to montage
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/forward/ft_apply_montage.m' at line 137
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/private/undobalancing.m' at line 37
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/ft_prepare_layout.m' at line 1275
 In '/imaging/local/software/spm_cbu_svn/releases/spm12_fil_r7771/external/fieldtrip/ft_prepare_layout.m' at line 592

creating layout for neuromag306 system


 JOB FAILED WITH ERROR: 
 unsupported value for first argument: html 
```

**Comment by tiborauer** [comment]
@ethanknights
I had some time to think about these modules, and I think it may not be the best idea to 'meeg'-ify them. The stream name 'meeg' would indicate that you can mix and match these modules, which you cannot, I presume. Currently, the 'meeg' stream contains EEGLab-formatted data.
I am sorry that this would put your work in vain...
Ideally, the best way would be to make the required legacy modules compatible with the new ones, but I cannot judge how much work it may require. Perhaps, not too much, and I am also happy to help. It would be beneficial for the CBU pipeline, because it could employ the new modules and e.g. aamod_meg_epoch` could be deleted rather than convolutedly renamed.

You said the main motivation of this PR is to get the CBU pipeline working with `aareport()`. Could you elaborate on it? There may be a simple way to bring back 'meg'; especially, because the maxfilter and perhaps Rik's ICA modules are MEG-specific.

Regarding the ` aamod_meg_denoise_ICA_2_applytrajectory` issue, I suspect it is due to some incompatibility, which we should be able to resolve soon.

**Comment by ethanknights** [comment]
Going to close this as getting stale - managed to workaround this a while ago, but might be worth coming revisiting at a later date (so I won't remove the branch for now).

**Pull request closed without merging**
